name: shadertoy_api
version: 1.0.0-dev.3
description: >-
  Main entities and contracts supported by the shadertoy REST and WEB APIs. 
  Can be used to create shadertoy web or persistent clients.
author: Ivo Leitão <ivo.leitao@gmail.com>
homepage: https://github.com/ivoleitao/shadertoy_api

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  equatable: ^1.0.0
  meta: ^1.1.8
  json_annotation: ^3.0.0

dev_dependencies:
  pedantic: ^1.8.0+1
  build_runner: ^1.7.2
  build_verify: ^1.1.1
  json_serializable: ^3.2.3
  test: ^1.9.4
  test_coverage: ^0.4.0
