name: shadertoy_api
version: 1.0.5
description: >-
  Main entities and contracts supported by the shadertoy REST and WEB APIs. 
  Can be used to create shadertoy web or persistent clients.
homepage: https://github.com/ivoleitao/shadertoy_api

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  equatable: ^1.2.5
  meta: ^1.2.4
  json_annotation: ^3.1.1

dev_dependencies:
  pedantic: ^1.9.2
  build_runner: ^1.10.11
  build_verify: ^1.1.1
  json_serializable: ^3.5.1
  test: ^1.15.7
  test_coverage: ^0.5.0
