name: shadertoy_api
version: 1.0.5
description: >-
  Main entities and contracts supported by the shadertoy REST and WEB APIs. 
  Can be used to create shadertoy web or persistent clients.
homepage: https://github.com/ivoleitao/shadertoy_api

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  equatable: ^1.2.3
  meta: ^1.2.2
  json_annotation: ^3.0.1

dev_dependencies:
  pedantic: ^1.9.2
  build_runner: ^1.10.0
  build_verify: ^1.1.1
  json_serializable: ^3.3.0
  test: ^1.15.3
  test_coverage: ^0.4.3
