name: shadertoy_api
version: 1.0.0-dev.8
description: >-
  Main entities and contracts supported by the shadertoy REST and WEB APIs. 
  Can be used to create shadertoy web or persistent clients.
author: Ivo Leitão <ivo.leitao@gmail.com>
homepage: https://github.com/ivoleitao/shadertoy_api

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  equatable: ^1.1.1
  meta: ^1.1.8
  json_annotation: ^3.0.1

dev_dependencies:
  pedantic: ^1.9.0
  build_runner: ^1.10.0
  build_verify: ^1.1.1
  json_serializable: ^3.3.0
  test: ^1.14.3
  test_coverage: ^0.4.1
