name: publish
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: google/dart:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: pub get
      - name: Install tools
        run: pub global activate remove_from_coverage
      - name: Run Formatter
        run: dartfmt -n --set-exit-if-changed .
      - name: Run Analyser
        run: dartanalyzer . --fatal-warnings
      - name: Run tests
        run: pub run test
      - name: Run Code Coverage
        run: pub run test_coverage
      - name: Remove generated files from lconv
        run: pub global run remove_from_coverage:remove_from_coverage -f coverage/lcov.info -r '.g.dart$'
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage/lcov.info
      - name: Add Pub Credentials
        run: echo '${{ secrets.PUB_CREDENTIALS }}' > ~/.pub-cache/credentials.json
      - name: Publish to Pub
        run: pub publish -f
